version: "3"

services:
  app-fe:
    container_name: app-fe
    build: ./web/
    image: reac_app_memt
    tty: true
    volumes:
      - ./web:/usr/src
    entrypoint: ./entrypoint.sh
    # working_dir: /usr/src
    environment:
      - PORT=3001
      - REACT_APP_WEBSITE_NAME=React on Docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
